language: python
dist: trusty
sudo: required
python:
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  postgresql: "9.6"
services:
  - postgresql
install:
  - pip install -r requirements_common.txt
  - pip install codeclimate-test-reporter
script:
  - flake8 .
  - cd tabbycat && coverage run manage.py test -v 2
