language: python
dist: trusty
sudo: required
group: edge
python:
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  postgresql: "9.6"
  chrome: stable
services:
  - postgresql
install:
  - pip install -r requirements_common.txt
  - pip install codeclimate-test-reporter
  - npm install
script:
  - flake8 .
  - cd tabbycat && coverage run manage.py test -v 2
# The below is used to enable selenium testing as per:
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_install:
  # Run google chrome in headless mode
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
  ⋮
before_script:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
