language: python
dist: trusty
sudo: required
python:
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  postgresql: "9.5"
services:
  - postgresql
install:
  - pip install -r requirements_common.txt
script:
  - flake8 tabbycat
  - cd tabbycat && dj test -v 2
