language: python
sudo: required
python:
  - "3.4"
  - "3.5"
addons:
  postgresql: "9.4"
services:
  - postgresql
install:
  - pip install -r requirements_common.txt
script:
  - flake8 tabbycat
  - cd tabbycat && dj test -v 2
