site_name: Tabby Cat Documentation
theme: readthedocs

docs_dir: .

pages:
- Home: 'index.md'
- Installation:
    - 'Introduction':                             'installation/intro.md'
    - 'Installing Online using Heroku':           'installation/heroku.md'
    - 'Installing Locally on Linux':              'installation/linux.md'
    - 'Installing Locally on OS X':               'installation/osx.md'
    - 'Installing Locally on Windows':            'installation/windows.md'
- Use:
    - 'Importing Tournament Data':  'use/importing-data.md'
    - 'Starting a Tournament':      'use/starting-a-tournament.md'
    - 'Running a Tournament':       'use/running-a-tournament.md'
    - 'Finishing a Tournament':     'use/finishing-a-tournament.md'
- Features:
    - 'Draw Generation':            'features/draw-generation.md'
    - 'Adjudicator Feedback':       'features/adjudicator-feedback.md'
    - 'Data Entry':                 'features/data-entry.md'
    - 'User Accounts':              'features/user-accounts-and-interfaces.md'
    - 'Team Standings':             'features/team-standings-rules.md'
    - 'Data Importers':             'features/data-importers.md'
    - 'Adjudicator Allocation':     'features/adjudicator-allocation.md'
    # - 'Public Interface':           'features/public-interface.md'
    # - 'Usage-Tracking':             'features/usage-tracking.md'
- About:
    - 'License':                    'about/license.md'
    - 'Authors':                    'about/authors.md'
    - 'Contributing':               'about/contributing.md'
    - 'Release Notes':              'about/release-notes.md'
    - 'Tournaments History':        'about/tournaments-history.md'
