site_name: Tabby Cat Documentation
theme: readthedocs

docs_dir: .

pages:
- Home: 'index.md'
- Installation:
    - '1 Introduction':               'installation/intro.md'
    - '2 On the Web using Heroku':    'installation/heroku.md'
    - '3 Locally on Linux':           'installation/linux.md'
    - '4 Locally on OS X':            'installation/osx.md'
    - '5 Locally on Windows':         'installation/windows.md'
- Use:
    - '1 Introduction':               'use/intro.md'
    - '2 Importing Tournament Data':  'use/importing-data.md'
    - '3 Starting a Tournament':      'use/starting-a-tournament.md'
    - '4 Running a Tournament':       'use/running-a-tournament.md'
    - '5 Finishing a Tournament':     'use/finishing-a-tournament.md'
- Feature Documentation:
    - '1 Introduction':               'features/intro.md'
    - '2 Draw Generation':            'features/draw-generation.md'
    - '3 Adjudicator Feedback':       'features/adjudicator-feedback.md'
    - '4 Data Entry':                 'features/data-entry.md'
    - '5 User Accounts':              'features/user-accounts-and-interfaces.md'
    - '6 Team Standings':             'features/team-standings-rules.md'
    - '7 Data Importers':             'features/data-importers.md'
    - '8 Adjudicator Allocation':     'features/adjudicator-allocation.md'
    # - 'Public Interface':           'features/public-interface.md'
    # - 'Usage-Tracking':             'features/usage-tracking.md'
- About:
    - '1 License':                    'about/license.md'
    - '2 Release Notes':              'about/release-notes.md'
    - '3 Versioning':                 'developer/versioning.md'
    - '4 Documentation':              'developer/documentation.md'
    - '5 Tournaments History':        'about/tournaments-history.md'


